import type { LevelMeta } from '../../lib/types';

const meta: LevelMeta = {
  id: 21,
  slug: 'the-correlation-mirage',
  title: 'The Correlation Mirage',
  tier: 'QUANT GAUNTLET',
  tagline: 'a 40×40 correlation matrix estimated from 250 days is mostly a rumor',
  brief: String.raw`A panel of 40 synthetic assets, 250 trading days. Their returns were generated by exactly **3 common factors** plus independent idiosyncratic noise — but you get only the sample: a $40 \times 40$ correlation matrix estimated from $T = 250$ observations, i.e. barely 6 observations per matrix entry.

Most of what that matrix tells you is fiction. Diagonalize it and the eigenvalues form a continuous "bulk" of pure estimation noise — with a few genuine spikes standing above. Your job: report **how many real factors exist**, and the eigenvalue level (the noise edge $\lambda_+$) below which structure cannot be distinguished from sampling error.

This is why naive Markowitz portfolios explode: they lean hardest on the smallest, least-real eigenvalues.`,
  recover: 'Recover the number of real factors and the Marchenko–Pastur noise edge λ₊.',
  starterCode: String.raw`# GROUND TRUTH · CASE 21 — The Correlation Mirage
names = [c for c in data.columns if c != "t"]
prices = data[names].to_numpy()
R = np.diff(np.log(prices), axis=0)     # 250 x 40 daily returns
T, N = R.shape
print("T =", T, " N =", N, " q = N/T =", N/T)

corr = np.corrcoef(R, rowvar=False)
eig = np.sort(np.linalg.eigvalsh(corr))[::-1]
plot_xy(np.arange(1, N+1), eig, label="eigenvalues (sorted)")
# where does noise end and structure begin? drawing that line
# by eye is not a method.
`,
  hints: {
    nudge: String.raw`If the data were **pure noise**, the eigenvalues of the sample correlation matrix would still spread out — into a precisely known shape. Anything consistent with that shape is uninformative. Anything above its upper edge is real.`,
    method: String.raw`Marchenko–Pastur: for iid noise with aspect ratio $q = N/T$, sample correlation eigenvalues fill $[\lambda_-, \lambda_+]$ with $\lambda_\pm = (1 \pm \sqrt{q})^2$. Here $q = 0.16$, so $\lambda_+ = 1.96$. Count eigenvalues above $\lambda_+$ → number of real factors; the edge itself is the second answer. Overlay the MP density on a histogram of the bulk (\`plot_xy\`) and watch 37 of your 40 eigenvalues snuggle into the noise curve.`,
    derivation: String.raw`Marchenko–Pastur (1967): if $X$ is $T \times N$ iid with unit variance, the eigenvalue distribution of $\tfrac1T X^\top X$ converges (as $N, T \to \infty$ with $N/T \to q$) to

$$\rho(\lambda) = \frac{\sqrt{(\lambda_+ - \lambda)(\lambda - \lambda_-)}}{2\pi q \lambda}, \qquad \lambda_\pm = (1 \pm \sqrt q)^2$$

The punchline is $\lambda_+ > 1$: even with **zero** true correlation, finite samples manufacture apparent structure up to eigenvalue $(1+\sqrt q)^2$. An eigenvalue of 1.9 in this panel means *nothing*. Estimation noise is not small here — with $N = 40, T = 250$ the matrix has 780 free correlations estimated from 250 vectors.

Factor spikes: a factor explaining fraction $\theta$ of total variance produces an eigenvalue $\approx N\theta$ (plus BBP finite-size corrections), which escapes the bulk when $N\theta > (1 + \sqrt q)^2$ — the three planted factors here clear it comfortably; the test suite verifies the 4th eigenvalue sits below the edge.

Why Markowitz explodes: the minimum-variance weights $w \propto \Sigma^{-1}\mu$ put mass $\propto 1/\lambda_i$ on each eigenvector — maximal leverage on exactly the eigen-directions that are *least real*. The RMT-clean recipe (Laloux–Bouchaud–Potters): keep eigenvalues above $\lambda_+$, replace the bulk with its average, reassemble. Same data, same math, an order of magnitude less fictional risk. "Knowing which part of your covariance matrix is real" is arguably the highest-value single fact in portfolio construction.`,
  },
  xLabel: 't (days)',
  yLabel: 'price',
};

export default meta;
